## Week 7 and 8 Exercise

In [1]:
# First I will import some needed libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import chardet

## Import xlsx File - CANDYDATA

In [2]:
Candy_Data = pd.read_excel("CANDYDATA.xlsx")
Candy_Data

/Users/Robyn/opt/anaconda3/lib/python3.8/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,ITEM,JOY,DESPAIR,NET FEELIES,NET CLOUT,DESPAIR (NEG)
0,York Peppermint Patties,634,78,556.0,1.639118,-78.0
1,Whole Wheat anything,21,419,-398.0,1.012938,-419.0
2,White Bread,15,473,-458.0,1.123440,-473.0
3,Vicodin,323,210,113.0,1.227036,-210.0
4,Twix,770,26,744.0,1.832497,-26.0
...,...,...,...,...,...,...
82,Black Jacks,34,252,-218.0,0.658410,-252.0
83,Any full-sized candy bar,828,13,815.0,1.936093,-13.0
84,Anonymous brown globs that come in black and o...,120,663,-543.0,1.802569,-663.0
85,100 Grand Bar,570,34,536.0,1.390488,-34.0
86,NaN,26204,17563,NaN,NaN,NaN

## Filter out missing data

In [3]:
# First I will use the .notnull function to see if any of the columns 
# are missing data or not
Candy_Data.notnull()

     ITEM   JOY  DESPAIR  NET FEELIES  NET CLOUT  DESPAIR (NEG)
0    True  True     True         True       True           True
1    True  True     True         True       True           True
2    True  True     True         True       True           True
3    True  True     True         True       True           True
4    True  True     True         True       True           True
..    ...   ...      ...          ...        ...            ...
82   True  True     True         True       True           True
83   True  True     True         True       True           True
84   True  True     True         True       True           True
85   True  True     True         True       True           True
86  False  True     True        False      False          False

[87 rows x 6 columns]

In [4]:
# As seen above it seems as if the only row that has returned a False 
# meaning we are missing data is row 86. Now I will use .dropna which 
# will drops out all rows containing missing data
Candy_Data.dropna()
# As seen below the only row that has been dropped was the last row 
# which only stated the totals.

,ITEM,JOY,DESPAIR,NET FEELIES,NET CLOUT,DESPAIR (NEG)
0,York Peppermint Patties,634,78,556.0,1.639118,-78.0
1,Whole Wheat anything,21,419,-398.0,1.012938,-419.0
2,White Bread,15,473,-458.0,1.123440,-473.0
3,Vicodin,323,210,113.0,1.227036,-210.0
4,Twix,770,26,744.0,1.832497,-26.0
...,...,...,...,...,...,...
81,Bonkers,31,99,-68.0,0.299277,-99.0
82,Black Jacks,34,252,-218.0,0.658410,-252.0
83,Any full-sized candy bar,828,13,815.0,1.936093,-13.0
84,Anonymous brown globs that come in black and o...,120,663,-543.0,1.802569,-663.0
85,100 Grand Bar,570,34,536.0,1.390488,-34.0

## Remove duplicates

In [5]:
# I will search and see if any of the columns have duplicate data 
# by using the format and duplicate function to state if the request is true or false
print("Is the 'ITEM' duplictaed: {}".format(any(Candy_Data.ITEM.duplicated())))
print("Is the 'JOY' duplictaed: {}".format(any(Candy_Data.JOY.duplicated())))
print("Is the 'DESPAIR' duplictaed: {}".format(any(Candy_Data.DESPAIR.duplicated())))
# As seen below we have duplicate data for both Joy and Despair which is
# not suprising as these columns are the number of times participants
# thought the item brought them Joy or Despair so we will not remove 
# any of these duplicates

Is the 'ITEM' duplictaed: False
Is the 'JOY' duplictaed: True
Is the 'DESPAIR' duplictaed: True

## Import xlsx File - BOING-BOING-CANDY-HIERARCHY-2016-SURVEY-Responses.xlsx

In [6]:
# First I will Import xlsx File - BOING-BOING-CANDY-HIERARCHY-2016-SURVEY-Responses.xlsx
Candy_Responses_Data = pd.read_excel("BOING-BOING-CANDY-HIERARCHY-2016-SURVEY-Responses.xlsx")
Candy_Responses_Data.head()

,Timestamp,Are you going actually going trick or treating yourself?,Your gender:,How old are you?,Which country do you live in?,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [BeyoncÃ©],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
0,2016-10-24 05:09:23.033,No,Male,22.0,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN
1,2016-10-24 05:09:54.798,No,Male,45.0,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
2,2016-10-24 05:13:06.734,No,Female,48.0,US,Colorado,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
3,2016-10-24 05:14:17.192,No,Male,57.0,usa,il,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN
4,2016-10-24 05:14:24.625,Yes,Male,42.0,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN

In [7]:
# Next I will use list and .columns function with dataframe object to 
# pull a list of my dataframes headers. 
list(Candy_Responses_Data.columns)

['Timestamp',
 'Are you going actually going trick or treating yourself?',
 'Your gender:',
 'How old are you?',
 'Which country do you live in?',
 'Which state, province, county do you live in?',
 ' [100 Grand Bar]',
 ' [Anonymous brown globs that come in black and orange wrappers]',
 ' [Any full-sized candy bar]',
 ' [Black Jacks]',
 ' [Bonkers (the candy)]',
 ' [Bonkers (the board game)]',
 ' [Bottle Caps]',
 " [Box'o'Raisins]",
 ' [Broken glow stick]',
 ' [Butterfinger]',
 ' [Cadbury Creme Eggs]',
 ' [Candy Corn]',
 ' [Candy that is clearly just the stuff given out for free at restaurants]',
 ' [Caramellos]',
 ' [Cash, or other forms of legal tender]',
 ' [Chardonnay]',
 ' [Chick-o-Sticks (we donâ€™t know what that is)]',
 ' [Chiclets]',
 ' [Coffee Crisp]',
 ' [Creepy Religious comics/Chick Tracts]',
 ' [Dental paraphenalia]',
 ' [Dots]',
 ' [Dove Bars]',
 ' [Fuzzy Peaches]',
 ' [Generic Brand Acetaminophen]',
 ' [Glow sticks]',
 ' [Goo Goo Clusters]',
 " [Good N' Plenty]",
 ' [Gum from baseball cards]',
 ' [Gummy Bears straight up]',
 ' [Hard Candy]',
 ' [Healthy Fruit]',
 ' [Heath Bar]',
 " [Hershey's Dark Chocolate]",
 ' [Hersheyâ€™s Milk Chocolate]',
 " [Hershey's Kisses]",
 ' [Hugs (actual physical hugs)]',
 ' [Jolly Rancher (bad flavor)]',
 ' [Jolly Ranchers (good flavor)]',
 ' [JoyJoy (Mit Iodine!)]',
 ' [Junior Mints]',
 ' [Senior Mints]',
 ' [Kale smoothie]',
 ' [Kinder Happy Hippo]',
 ' [Kit Kat]',
 ' [LaffyTaffy]',
 ' [LemonHeads]',
 ' [Licorice (not black)]',
 ' [Licorice (yes black)]',
 ' [Lindt Truffle]',
 ' [Lollipops]',
 ' [Mars]',
 ' [Mary Janes]',
 ' [Maynards]',
 ' [Mike and Ike]',
 ' [Milk Duds]',
 ' [Milky Way]',
 ' [Regular M&Ms]',
 ' [Peanut M&Mâ€™s]',
 " [Blue M&M's]",
 " [Red M&M's]",
 " [Third Party M&M's]",
 ' [Minibags of chips]',
 ' [Mint Kisses]',
 ' [Mint Juleps]',
 ' [Mr. Goodbar]',
 ' [Necco Wafers]',
 ' [Nerds]',
 ' [Nestle Crunch]',
 " [Now'n'Laters]",
 ' [Peeps]',
 ' [Pencils]',
 ' [Person of Interest Season 3 DVD Box Set (not including Disc 4 with hilarious outtakes)]',
 ' [Pixy Stix]',
 ' [Reeseâ€™s Peanut Butter Cups]',
 " [Reese's Pieces]",
 ' [Reggie Jackson Bar]',
 ' [Rolos]',
 ' [Skittles]',
 ' [Smarties (American)]',
 ' [Smarties (Commonwealth)]',
 ' [Snickers]',
 ' [Sourpatch Kids (i.e. abominations of nature)]',
 ' [Spotted Dick]',
 ' [Starburst]',
 ' [Sweet Tarts]',
 ' [Swedish Fish]',
 ' [Sweetums (a friend to diabetes)]',
 ' [Tic Tacs]',
 ' [Those odd marshmallow circus peanut things]',
 ' [Three Musketeers]',
 ' [Tolberone something or other]',
 ' [Trail Mix]',
 ' [Twix]',
 ' [Vials of pure high fructose corn syrup, for main-lining into your vein]',
 ' [Vicodin]',
 ' [Whatchamacallit Bars]',
 ' [White Bread]',
 ' [Whole Wheat anything]',
 ' [York Peppermint Patties]',
 'Please list any items not included above that give you JOY.',
 'Please list any items not included above that give you DESPAIR.',
 'Please leave any witty, snarky or thoughtful remarks or comments regarding your choices.',
 'Guess the number of mints in my hand.',
 'Betty or Veronica?',
 '"That dress* that went viral a few years back - when I first saw it, it was ________"',
 'What is your favourite font?',
 'Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling]',
 'Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams]',
 'Please estimate the degree(s) of separation you have from the following celebrities [BeyoncÃ©]',
 'Please estimate the degree(s) of separation you have from the following celebrities [Bieber]',
 'Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon]',
 'Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)]',
 'Which day do you prefer, Friday or Sunday?',
 'Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?',
 'When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).',
 ' [York Peppermint Patties] Ignore']

In [8]:
# I will use pandas .rename function to edit my headers names. 
Candy_Responses_Data=Candy_Responses_Data.rename(columns={'Are you going actually going trick or treating yourself?':'Trick_or_Treating', 
                                  'Your gender:':'Gender',
                                  'How old are you?':'Age','Which country do you live in?':'Country',
                                                    'Which state, province, county do you live in?':'State',
                                                    '[Butterfinger]':'Butterfinger'})
Candy_Responses_Data.head()

,Timestamp,Trick_or_Treating,Gender,Age,Country,State,[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [BeyoncÃ©],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
0,2016-10-24 05:09:23.033,No,Male,22.0,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN
1,2016-10-24 05:09:54.798,No,Male,45.0,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
2,2016-10-24 05:13:06.734,No,Female,48.0,US,Colorado,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
3,2016-10-24 05:14:17.192,No,Male,57.0,usa,il,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN
4,2016-10-24 05:14:24.625,Yes,Male,42.0,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN

## Reshape DataFrame

In [9]:
# I will reshape the data by selecting only the data that has individuals that are 
# trick or treating to see what their opinions are for each candy
Trick_or_Treaters_Data = Candy_Responses_Data[Candy_Responses_Data['Trick_or_Treating'] == 'Yes']
Trick_or_Treaters_Data.head()

,Timestamp,Trick_or_Treating,Gender,Age,Country,State,[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [BeyoncÃ©],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
4,2016-10-24 05:14:24.625,Yes,Male,42.0,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN
6,2016-10-24 05:16:50.572,Yes,Male,47.0,usa,il,DESPAIR,DESPAIR,JOY,DESPAIR,...,2,3 or higher,3 or higher,2,2,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
8,2016-10-24 05:17:49.292,Yes,Male,44.0,USA,PA,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,2,3 or higher,2,2,Friday,East to West,ESPN,NaN
13,2016-10-24 05:22:12.699,Yes,Male,45.0,Japan,Tokyo,MEH,DESPAIR,MEH,DESPAIR,...,2,2,3 or higher,3 or higher,2,2,Sunday,East to West,Science: Latest News and Headlines,NaN
18,2016-10-24 05:26:35.167,Yes,Male,49.0,USA,NJ,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,I cut them and eat with cheese or peanut butter,ESPN,NaN

## Fill in Missing Data

In [10]:
# First I will use the .notnull function to see if any of the columns 
# are missing data or not
Candy_Responses_Data.notnull()
# As seen below we see that we are missing some data.

,Timestamp,Trick_or_Treating,Gender,Age,Country,State,[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [BeyoncÃ©],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1218,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
1219,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
1220,True,True,True,False,False,False,True,True,True,False,...,False,False,False,False,False,False,True,True,True,False
1221,True,True,True,True,True,True,False,True,True,True,...,True,True,True,True,True,True,True,True,True,False
1222,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False

In [11]:
# Being that we are missing data and I do not want to just drop the 
# rows with missing data I have decided to use the .fillna function 
# to ffill and bfill the data which meanse if there is nothing above 
# we will back fill the data but if there is data in front we will 
# front fill the missing data
Candy_Responses_Data = Candy_Responses_Data.fillna(method='ffill').fillna(method='bfill')
Candy_Responses_Data

,Timestamp,Trick_or_Treating,Gender,Age,Country,State,[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [BeyoncÃ©],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
0,2016-10-24 05:09:23.033,No,Male,22.0,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN
1,2016-10-24 05:09:54.798,No,Male,45.0,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
2,2016-10-24 05:13:06.734,No,Female,48.0,US,Colorado,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
3,2016-10-24 05:14:17.192,No,Male,57.0,usa,il,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN
4,2016-10-24 05:14:24.625,Yes,Male,42.0,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1218,2016-10-29 16:53:52.516,No,Female,52.0,USA,TX,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,2,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
1219,2016-10-30 06:53:54.735,No,Male,33.0,united states,minnesota,JOY,DESPAIR,JOY,DESPAIR,...,"Actually, that's me.",3 or higher,3 or higher,3 or higher,3 or higher,"Actually, that's me.",Friday,Sinusoidally around the equator,Science: Latest News and Headlines,NaN
1220,2016-10-30 11:06:10.827,No,Male,33.0,united states,minnesota,JOY,MEH,JOY,DESPAIR,...,"Actually, that's me.",3 or higher,3 or higher,3 or higher,3 or higher,"Actually, that's me.",Sunday,nne to east to nnw to s to n,Science: Latest News and Headlines,NaN
1221,2016-10-30 16:07:26.539,No,Male,48.0,canada,BC,JOY,DESPAIR,JOY,DESPAIR,...,1,2,3 or higher,3 or higher,2,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
1222,2016-10-30 17:06:45.660,Yes,Female,44.0,Us,Nh,JOY,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Daily Dish,NaN

In [12]:
# Next I will use .dropna to get rid of any other NaN that are 
# remaining that have not been taken care of

## Pivot DataFrame

In [13]:
# Now that the missing data is filled we can create a pivot that the 
# indext is on the timestamp while the columns will be for Trick_or_Treating 
# and we will determine the age for our values which will tell us how old the 
# tricker treaters are.
Pivot_Candy_SURVEY_Data = Candy_Responses_Data.pivot(index='Timestamp', columns='Trick_or_Treating', values='Age')
Pivot_Candy_SURVEY_Data.head()
# As seen Below we have NaN due to the fact that either the individual 
# said yes or no to the fact that they went tricker treating

Trick_or_Treating          No   Yes
Timestamp
2016-10-24 05:09:23.033  22.0   NaN
2016-10-24 05:09:54.798  45.0   NaN
2016-10-24 05:13:06.734  48.0   NaN
2016-10-24 05:14:17.192  57.0   NaN
2016-10-24 05:14:24.625   NaN  42.0

## Grouping with Dicts/Series

In [14]:
# First I will create a new DataFrame that shows just the Gender and Age
Updated_Candy_Responses_Data = Candy_Responses_Data.filter(['Gender','Age'], axis=1)
Updated_Candy_Responses_Data

      Gender   Age
0       Male  22.0
1       Male  45.0
2     Female  48.0
3       Male  57.0
4       Male  42.0
...      ...   ...
1218  Female  52.0
1219    Male  33.0
1220    Male  33.0
1221    Male  48.0
1222  Female  44.0

[1223 rows x 2 columns]

In [18]:
# Next I will use the .groupby function to bring together the Pivot_Candy_SURVEY_Data
# and show
Updated_Candy_Responses_Data.groupby(['Gender']).mean()
# As we can see the average age for a female is 38.34 and the average 
# age of a male is 42.23

                          Age
Gender
Female              38.343137
I'd rather not say  38.550000
Male                42.230334
Other               33.176471

## Crosstab

In [25]:
# I will a simple cross-tabulation of two or more factors from our 
# dataframe through the use of .crosstab
pd.crosstab(Updated_Candy_Responses_Data['Age'], Updated_Candy_Responses_Data['Gender'])
# Seen below is the amount of males, females, others, and I'd rather 
# not say genders that are for each age group

Gender  Female  I'd rather not say  Male  Other
Age
7.0          1                   0     0      0
10.0         2                   0     0      0
11.0         1                   0     0      0
12.0         1                   0     0      0
13.0         2                   0     0      0
...        ...                 ...   ...    ...
78.0         0                   1     0      0
79.0         0                   0     1      0
81.0         1                   0     0      0
82.0         1                   0     0      0
142.0        0                   0     1      0

[69 rows x 4 columns]

## Convert timestamps to periods and back

In [42]:
from datetime import datetime

In [44]:
# Created a date and time string from our data frame
Candy_date_time_str = Candy_Responses_Data.Timestamp
Candy_date_time_str

0      2016-10-24 05:09:23.033
1      2016-10-24 05:09:54.798
2      2016-10-24 05:13:06.734
3      2016-10-24 05:14:17.192
4      2016-10-24 05:14:24.625
                 ...
1218   2016-10-29 16:53:52.516
1219   2016-10-30 06:53:54.735
1220   2016-10-30 11:06:10.827
1221   2016-10-30 16:07:26.539
1222   2016-10-30 17:06:45.660
Name: Timestamp, Length: 1223, dtype: datetime64[ns]

In [50]:
# Next I will use the to_datetime to convert a string to a date in python
Candy_date_time_obj = pd.to_datetime(Candy_date_time_str, format= '%d/%m/%y %H:%M:%S')
Candy_date_time_obj

0      2016-10-24 05:09:23.033
1      2016-10-24 05:09:54.798
2      2016-10-24 05:13:06.734
3      2016-10-24 05:14:17.192
4      2016-10-24 05:14:24.625
                 ...
1218   2016-10-29 16:53:52.516
1219   2016-10-30 06:53:54.735
1220   2016-10-30 11:06:10.827
1221   2016-10-30 16:07:26.539
1222   2016-10-30 17:06:45.660
Name: Timestamp, Length: 1223, dtype: datetime64[ns]

## Generate date range

In [51]:
# first I will ensure that the timestamp column is in date format
Candy_Responses_Data['Timestamp'] = pd.to_datetime(Candy_Responses_Data['Timestamp'])

In [52]:
# next I will create a start date and end date to filter the data 
# frame with
start_date = '2016-10-24 05:14:24.625'
end_date = '2016-10-29 16:53:52.516'

In [53]:
# Next I will create a mask that will be applied to the dataframe to 
# filter it
Candy_Mask = (Candy_Responses_Data['Timestamp'] > start_date) & (Candy_Responses_Data['Timestamp'] <= end_date)

In [54]:
Masked_Candy_Data = Candy_Responses_Data.loc[Candy_Mask]
Masked_Candy_Data
# As seen below we have removed several lines from this data frame by 
# excluding dates that did not fall within the time frame

,Timestamp,Trick_or_Treating,Gender,Age,Country,State,[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [BeyoncÃ©],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
5,2016-10-24 05:16:43.126,No,Male,41.0,USA,Georgia,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
6,2016-10-24 05:16:50.572,Yes,Male,47.0,usa,il,DESPAIR,DESPAIR,JOY,DESPAIR,...,2,3 or higher,3 or higher,2,2,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
7,2016-10-24 05:16:55.324,No,Male,28.0,Canada,Ontario,MEH,JOY,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
8,2016-10-24 05:17:49.292,Yes,Male,44.0,USA,PA,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,2,3 or higher,2,2,Friday,East to West,ESPN,NaN
9,2016-10-24 05:18:51.021,No,Female,41.0,UK,PA,DESPAIR,DESPAIR,JOY,DESPAIR,...,2,1,3 or higher,3 or higher,3 or higher,"Actually, that's me.",Sunday,"north to south, but tilted 90 degrees with ste...",ESPN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1214,2016-10-29 10:53:26.543,No,Male,35.0,USA,Massachusetts,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
1215,2016-10-29 11:56:55.930,No,Female,34.0,United State,New Hampshire,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
1216,2016-10-29 12:02:52.773,Yes,Female,56.0,USA,NH,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,1,3 or higher,Friday,East to West,ESPN,NaN
1217,2016-10-29 14:47:43.907,No,Male,54.0,USA,wisconisin,MEH,MEH,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,"Actually, that's me.",Friday,Pureed,Science: Latest News and Headlines,NaN
1218,2016-10-29 16:53:52.516,No,Female,52.0,USA,TX,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,2,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN